export default class SpawnCard {
  id = null

  constructor(id) {
    this.id = id
  }
}

export const masterSpawnDeck = [
  new SpawnCard(1),
  new SpawnCard(2),
  new SpawnCard(3),
  new SpawnCard(4),
  new SpawnCard(5),
  new SpawnCard(6),
  new SpawnCard(7),
  new SpawnCard(8),
  new SpawnCard(9),
  new SpawnCard(10),
  new SpawnCard(11),
  new SpawnCard(12),
  new SpawnCard(13),
  new SpawnCard(14),
  new SpawnCard(15),
  new SpawnCard(16),
  new SpawnCard(17),
  new SpawnCard(18),
  new SpawnCard(19),
  new SpawnCard(20),
  new SpawnCard(21),
  new SpawnCard(22),
  new SpawnCard(23),
  new SpawnCard(24),
  new SpawnCard(25),
  new SpawnCard(26),
  new SpawnCard(27),
  new SpawnCard(28),
  new SpawnCard(29), // Abomination
  new SpawnCard(29),
  new SpawnCard(29),
  new SpawnCard(29),
  new SpawnCard(30),
  new SpawnCard(31),
  new SpawnCard(32),
  new SpawnCard(33),
  new SpawnCard(34),
  new SpawnCard(35),
  new SpawnCard(36),
  new SpawnCard(37),
  new SpawnCard(38),
  new SpawnCard(39),
  new SpawnCard(40),
  new SpawnCard(43),
  new SpawnCard(46),
  new SpawnCard(50),
  new SpawnCard(54),
  new SpawnCard(55),
  new SpawnCard(58),
  new SpawnCard(59),
  new SpawnCard(62),
  new SpawnCard(63),
  new SpawnCard(66),
  new SpawnCard(67),
  new SpawnCard(69),
  new SpawnCard(74),
  new SpawnCard(75),
  new SpawnCard(77),
  new SpawnCard(81),
  new SpawnCard(85),
  new SpawnCard(86),
  new SpawnCard(87),
  new SpawnCard(89),
  new SpawnCard(160),
  new SpawnCard(168),
  new SpawnCard(169),
  new SpawnCard(171),
  new SpawnCard(176),
  new SpawnCard(235),
  new SpawnCard(236),
  new SpawnCard(237),
  new SpawnCard(238),
  new SpawnCard(239),
]

export const mapSpawnDeck = (cardId) => masterSpawnDeck.find(card => card.id === cardId)

export const initSpawnDeck = masterSpawnDeck.map((card) => card.id)
